name: Update Tile Index

# on:
#   push:
#     branches:
#       - dop_nw
#
# jobs:
#   update-version-number:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3
#       - name: Update DOP Tile Index NW
#         run: |
#           echo hello > DOP/NW/test.txt
#       - name: Commit Changes
#         run: |
#           git config user.name "$GITHUB_ACTOR"
#           git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
#           git checkout -b pypi
#           git commit -a -m "Update tile index"
#           git push origin dop_nw

# name: Continuous Integration
on:
  push:
    branches:
      - dop_nw
jobs:
  update-tindex-dop-nw:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Commit and push all changed files.
    - name: GIT Commit Build Artifacts (coverage, dist, devdist, docs)
      # Only run on main branch push (e.g. after pull request merge).
      run: |
        echo hello > DOP/NW/test.txt
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add DOP/NW/test2.txt
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push

# name: Tile index DOP NW
#
# on:
#   release:
#     types: [published]
#
# jobs:
#   tindex_dop_nw:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v3
#       # with:
#       #   path: "."
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v2
#     - name: Creation of tindex
#       id: docker_build
#       uses: docker/build-push-action@v2
#       with:
#         push: false
#         tags: tindex_creation
#         context: .
#         file: docker/Dockerfile
#         no-cache: true
#         # pull: true
#     # - run: mkdir -p artifact
#     # - run: echo hello > artifact/world.txt
#     # - uses: actions/upload-artifact@v3
#     #   with:
#     #     name: helloworld
#     #     path: artifact/world.txt
#     - name: Upload tindex
#       run: |
#         echo hello > DOP/NW/test.txt
#         git config user.name github-actions
#         git config user.email weinmann@mundialis.de
#         git add DOP/NW/test.txt
#         git commit -m "Upade tile index DOP NW"
#         git push origin main
