name: Tile index DOP NW

on:
  release:
    types: [published]

jobs:
  tindex_dop_nw:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      # with:
      #   path: "."
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Creation of tindex
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: tindex_creation
        context: .
        file: docker/Dockerfile
        no-cache: true
        # pull: true
    # - run: mkdir -p artifact
    # - run: echo hello > artifact/world.txt
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: helloworld
    #     path: artifact/world.txt
    - name: Upload tindex
      run: |
        echo hello > DOP/NW/test.txt
        git config user.name github-actions
        git config user.email weinmann@mundialis.de
        git add DOP/NW/test.txt
        git commit -m "Upade tile index DOP NW"
        git push
